name: ci

on:
  push:
    branches:
      - main
    
jobs:
  push_to_registry:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo curl -fL https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64 -o /bin/yq
          sudo chmod +x /bin/yq

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - name: Test
        working-directory: .
        run: go test -v ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - id: get-sha
        run: |
          commit=${{ github.sha }}
          sha=${commit:0:7}
          echo "::set-output name=sha::$sha"
          
      - name: Build Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: minghsu0107/cicd-demo-ga-remote:${{ github.ref_name }}-${{ steps.get-sha.outputs.sha }},minghsu0107/cicd-demo-ga-remote:latest

      - name: Update Manifests - Production
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          IMAGE_TAG: ${{ github.ref_name }}-${{ steps.get-sha.outputs.sha }}
          COMMIT_SHA: ${{ steps.get-sha.outputs.sha }}
        run: |
          mkdir -p ~/.ssh && echo $SSH_KEY | base64 -d > ~/.ssh/id_rsa && chmod 700 ~/.ssh/id_rsa && ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone ssh://git@github.com/minghsu0107/cicd-demo-remote-manifests.git && cd cicd-demo-remote-manifests && git checkout main
          cd overlays/production

          kustomize edit set image minghsu0107/cicd-demo-ga-remote:$IMAGE_TAG

          yq '.resources[0]' kustomization.yaml > /tmp/input.txt
          REMOTE_URL=`cut -d'?' -f1 /tmp/input.txt`
          yq -i '.resources[0] = "'$REMOTE_URL'?ref='$COMMIT_SHA'"' kustomization.yaml

          git config --global user.name minghsu0107
          git config --global user.email minghsu0107@gmail.com
          git add . && git commit --allow-empty -m "🚀 update to $IMAGE_TAG"
          git push ssh://git@github.com/minghsu0107/cicd-demo-remote-manifests.git
